# Generated by Django 5.2.5 on 2025-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('en_proceso', 'En Proceso')], default='abierta', max_length=20),
        ),
    ]
