# Generated by Django 5.2.5 on 2025-10-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0002_alter_vacante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='empresa',
            field=models.CharField(max_length=150),
        ),
    ]
